# DigitalOcean App Platform Configuration
# Alternative location for app configuration

name: ai-recruitment-platform
region: nyc

# Database
databases:
  - name: ai-recruitment-db
    engine: PG
    version: "15"
    production: true

# Backend API
services:
  - name: api
    source_dir: /
    github:
      repo: your-username/ai-recruitment-platform
      branch: main
      deploy_on_push: true
    
    build_command: pip install -r requirements.txt
    run_command: ./scripts/prestart.sh && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    
    health_check:
      http_path: /health
    
    envs:
      - key: DATABASE_URL
        value: "${ai-recruitment-db.DATABASE_URL}"
      - key: JWT_SECRET_KEY
        value: "${JWT_SECRET_KEY}"
        type: SECRET
      - key: OPENAI_API_KEY
        value: "${OPENAI_API_KEY}"
        type: SECRET
    
    routes:
      - path: /api
      - path: /health

  # Frontend
  - name: web
    source_dir: /frontend
    github:
      repo: your-username/ai-recruitment-platform
      branch: main
      deploy_on_push: true
    
    build_command: npm ci && npm run build
    run_command: npm start
    
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    
    envs:
      - key: NEXT_PUBLIC_API_BASE_URL
        value: "https://${APP_DOMAIN}/api"
    
    routes:
      - path: /

# Pre-deploy migration
jobs:
  - name: db-migrate
    source_dir: /
    run_command: alembic upgrade head
    environment_slug: python
    instance_size_slug: basic-xxs
    kind: PRE_DEPLOY
    envs:
      - key: DATABASE_URL
        value: "${ai-recruitment-db.DATABASE_URL}"