services:
  # FastAPI Application
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      # Enable dev auth bypass inside the container for local testing
      - DEV_BEARER_TOKEN=${DEV_BEARER_TOKEN:-dev-123}
      - DEV_USER_ROLE=${DEV_USER_ROLE:-manager}
      - DEV_USER_ID=${DEV_USER_ID:-1}
      - DEV_TENANT_ID=${DEV_TENANT_ID:-1}
    restart: unless-stopped