"""add invites and password_resets

Revision ID: 1366f1730754
Revises: add_enrichment_fields_20250911
Create Date: 2025-09-15 21:23:37.627275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1366f1730754'
down_revision = 'add_enrichment_fields_20250911'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###