"""add created_at and composite indexes to notifications

Revision ID: 207693ea7057
Revises: b60117ed9d39
Create Date: 2025-09-09 02:55:03.871959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207693ea7057'
down_revision = 'b60117ed9d39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_user_created_at', 'notifications', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_user_created_at', table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    # ### end Alembic commands ###