"""add recruiter_directory table

Revision ID: aefcc3eb170b
Revises: 1366f1730754
Create Date: 2025-09-17 14:04:43.218934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aefcc3eb170b'
down_revision = '1366f1730754'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recruiter_candidate_notes_candidate_id'), table_name='recruiter_candidate_notes')
    op.drop_index(op.f('ix_recruiter_candidate_notes_id'), table_name='recruiter_candidate_notes')
    op.drop_index(op.f('ix_recruiter_candidate_notes_key'), table_name='recruiter_candidate_notes')
    op.drop_index(op.f('ix_recruiter_candidate_notes_recruiter_identifier'), table_name='recruiter_candidate_notes')
    op.drop_table('recruiter_candidate_notes')
    op.drop_index(op.f('ix_recruiter_candidate_activities_candidate_id'), table_name='recruiter_candidate_activities')
    op.drop_index(op.f('ix_recruiter_candidate_activities_id'), table_name='recruiter_candidate_activities')
    op.drop_index(op.f('ix_recruiter_candidate_activities_job_id'), table_name='recruiter_candidate_activities')
    op.drop_index(op.f('ix_recruiter_candidate_activities_recruiter_identifier'), table_name='recruiter_candidate_activities')
    op.drop_index(op.f('ix_recruiter_candidate_activities_run_id'), table_name='recruiter_candidate_activities')
    op.drop_index(op.f('ix_recruiter_candidate_activity_key'), table_name='recruiter_candidate_activities')
    op.drop_table('recruiter_candidate_activities')
    op.drop_index(op.f('ix_recruiter_candidate_documents_candidate_id'), table_name='recruiter_candidate_documents')
    op.drop_index(op.f('ix_recruiter_candidate_documents_id'), table_name='recruiter_candidate_documents')
    op.drop_index(op.f('ix_recruiter_candidate_documents_key'), table_name='recruiter_candidate_documents')
    op.drop_index(op.f('ix_recruiter_candidate_documents_recruiter_identifier'), table_name='recruiter_candidate_documents')
    op.drop_table('recruiter_candidate_documents')
    op.drop_index(op.f('ix_recruiter_candidate_profiles_candidate_id'), table_name='recruiter_candidate_profiles')
    op.drop_index(op.f('ix_recruiter_candidate_profiles_id'), table_name='recruiter_candidate_profiles')
    op.drop_index(op.f('ix_recruiter_candidate_profiles_recruiter_identifier'), table_name='recruiter_candidate_profiles')
    op.drop_table('recruiter_candidate_profiles')
    op.drop_index(op.f('ix_recruiter_candidate_interviews_candidate_id'), table_name='recruiter_candidate_interviews')
    op.drop_index(op.f('ix_recruiter_candidate_interviews_id'), table_name='recruiter_candidate_interviews')
    op.drop_index(op.f('ix_recruiter_candidate_interviews_job_id'), table_name='recruiter_candidate_interviews')
    op.drop_index(op.f('ix_recruiter_candidate_interviews_key'), table_name='recruiter_candidate_interviews')
    op.drop_index(op.f('ix_recruiter_candidate_interviews_recruiter_identifier'), table_name='recruiter_candidate_interviews')
    op.drop_table('recruiter_candidate_interviews')
    op.drop_index(op.f('ix_recruiter_candidate_comms_key'), table_name='recruiter_candidate_communications')
    op.drop_index(op.f('ix_recruiter_candidate_communications_candidate_id'), table_name='recruiter_candidate_communications')
    op.drop_index(op.f('ix_recruiter_candidate_communications_id'), table_name='recruiter_candidate_communications')
    op.drop_index(op.f('ix_recruiter_candidate_communications_recruiter_identifier'), table_name='recruiter_candidate_communications')
    op.drop_table('recruiter_candidate_communications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruiter_candidate_communications',
    sa.Column('candidate_id', sa.INTEGER(), nullable=False),
    sa.Column('recruiter_identifier', sa.VARCHAR(length=255), nullable=False),
    sa.Column('communication_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['recruiter_candidate_names.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiter_candidate_communications_recruiter_identifier'), 'recruiter_candidate_communications', ['recruiter_identifier'], unique=False)
    op.create_index(op.f('ix_recruiter_candidate_communications_id'), 'recruiter_candidate_communications', ['id'], unique=False)
    op.create_index(op.f('ix_recruiter_candidate_communications_candidate_id'), 'recruiter_candidate_communications', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_recruiter_candidate_comms_key'), 'recruiter_candidate_communications', ['recruiter_identifier', 'candidate_id', 'created_at'], unique=False)
    op.create_table('recruiter_candidate_interviews',
    sa.Column('candidate_id', sa.INTEGER(), nullable=False),
    sa.Column('recruiter_identifier', sa.VARCHAR(length=255), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('interview_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('job_id', sa.INTEGER(), nullable=True),
    sa.Column('scheduled_at', sa.DATETIME(), nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), nullable=True),
    sa.Column('location', sa.VARCHAR(length=500), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['recruiter_candidate_names.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiter_candidate_interviews_recruiter_identifier'), 'recruiter_candidate_interviews', ['recruiter_identifier'], unique=False)
    op.create_index(op.f('ix_recruiter_candidate_interviews_key'), 'recruiter_candidate_interviews', ['recruiter_identifier', 'candidate_id', 'scheduled_at'], unique=False)
    op.create_index(op.f('ix_recruiter_candidate_interviews_job_id'), 'recruiter_candidate_interviews', ['job_id'], unique=False)
    op.create_index(op.f('ix_recruiter_candidate_interviews_id'), 'recruiter_candidate_interviews', ['id'], unique=False)
    op.create_index(op.f('ix_recruiter_candidate_interviews_candidate_id'), 'recruiter_candidate_interviews', ['candidate_id'], unique=False)
    op.create_table('recruiter_candidate_profiles',
    sa.Column('candidate_id', sa.INTEGER(), nullable=False),
    sa.Column('recruiter_identifier', sa.VARCHAR(length=255), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('company', sa.VARCHAR(length=255), nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('last_activity_at', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['recruiter_candidate_names.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiter_candidate_profiles_recruiter_identifier'), 'recruiter_candidate_profiles', ['recruiter_identifier'], unique=False)
    op.create_index(op.f('ix_recruiter_candidate_profiles_id'), 'recruiter_candidate_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_recruiter_candidate_profiles_candidate_id'), 'recruiter_candidate_profiles', ['candidate_id'], unique=1)
    op.create_table('recruiter_candidate_documents',
    sa.Column('candidate_id', sa.INTEGER(), nullable=False),
    sa.Column('recruiter_identifier', sa.VARCHAR(length=255), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=500), nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('storage_path', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=150), nullable=True),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['recruiter_candidate_names.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiter_candidate_documents_recruiter_identifier'), 'recruiter_candidate_documents', ['recruiter_identifier'], unique=False)
    op.create_index(op.f('ix_recruiter_candidate_documents_key'), 'recruiter_candidate_documents', ['recruiter_identifier', 'candidate_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_recruiter_candidate_documents_id'), 'recruiter_candidate_documents', ['id'], unique=False)
    op.create_index(op.f('ix_recruiter_candidate_documents_candidate_id'), 'recruiter_candidate_documents', ['candidate_id'], unique=False)
    op.create_table('recruiter_candidate_activities',
    sa.Column('candidate_id', sa.INTEGER(), nullable=False),
    sa.Column('recruiter_identifier', sa.VARCHAR(length=255), nullable=False),
    sa.Column('type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('job_id', sa.INTEGER(), nullable=True),
    sa.Column('run_id', sa.INTEGER(), nullable=True),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.Column('occurred_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['recruiter_candidate_names.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiter_candidate_activity_key'), 'recruiter_candidate_activities', ['recruiter_identifier', 'candidate_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_recruiter_candidate_activities_run_id'), 'recruiter_candidate_activities', ['run_id'], unique=False)
    op.create_index(op.f('ix_recruiter_candidate_activities_recruiter_identifier'), 'recruiter_candidate_activities', ['recruiter_identifier'], unique=False)
    op.create_index(op.f('ix_recruiter_candidate_activities_job_id'), 'recruiter_candidate_activities', ['job_id'], unique=False)
    op.create_index(op.f('ix_recruiter_candidate_activities_id'), 'recruiter_candidate_activities', ['id'], unique=False)
    op.create_index(op.f('ix_recruiter_candidate_activities_candidate_id'), 'recruiter_candidate_activities', ['candidate_id'], unique=False)
    op.create_table('recruiter_candidate_notes',
    sa.Column('candidate_id', sa.INTEGER(), nullable=False),
    sa.Column('recruiter_identifier', sa.VARCHAR(length=255), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('note_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('is_private', sa.INTEGER(), nullable=False),
    sa.Column('tags', sa.VARCHAR(length=500), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['recruiter_candidate_names.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiter_candidate_notes_recruiter_identifier'), 'recruiter_candidate_notes', ['recruiter_identifier'], unique=False)
    op.create_index(op.f('ix_recruiter_candidate_notes_key'), 'recruiter_candidate_notes', ['recruiter_identifier', 'candidate_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_recruiter_candidate_notes_id'), 'recruiter_candidate_notes', ['id'], unique=False)
    op.create_index(op.f('ix_recruiter_candidate_notes_candidate_id'), 'recruiter_candidate_notes', ['candidate_id'], unique=False)
    # ### end Alembic commands ###